### ISSUE TITLE
New Language Support

### ISSUE THREAD

**Issue by frios** [mchakravarty/CodeEditorView#33]
Is there an easy way of adding new language support? I am really interested in using this library to support another language. Right now, it looks like the only way to do so is to change the LanguageConfiguration file. If that is true, it would be nice to be able to create an external file for my own language support that gets added to the existing language support. That way, anybody can create and submit language configurations to the project.

**Comment by mchakravarty** [comment]
Generally speaking, you don't need to change `LanguageConfiguration.swift`. Instead, you can define an extension of the `LanguageConfiguration` struct outside of the package (e.g., in your app). However, in order to add an additional language to the package, yes, extending `LanguageConfiguration.swift` would be the way to go (adding a `public static let` just like that's currently being done for Swift and Haskell). I'd be more than happy to merge a pull request that does that for other languages.

Being able to load a language configuration from an external file would surely be useful if somebody uses `CodeEditorView` to build for a general purpose editor that allows users to download and/or write configurations for additional languages. Maybe it would be as simple as making `LanguageConfiguration` conform to the `Decodable` protocol. Then, language configurations could be defined as property lists or JSON.

For configurations that are included into the package itself, my preference would be to define them as constants in Swift (as done so far). That way, if the language configuration struct changes, the Swift compiler will pick up any provided language configurations that have not been updated in sync. (With external files, we'd need an extra test that loads all language configurations one-by-one to check that they are still valid.)

**Comment by frios** [comment]
Thank you. I am attempting to do just that. The problem I am running into is that all of your Helpers, etc are declared private so I cannot access them in my extension file.

**Comment by mchakravarty** [comment]
Which ones do you need? Only the generic `group(_:)` and `alternatives(_:)` or also more specific ones?

I don't mind exposing more, but I think, I need to make the naming clearer in that case.

**Comment by frios** [comment]
Honestly, I suck at RegEx and I have not had the time to sit and decipher them yet. Where I am getting compile errors are with the Helpers, idHeadChar, idBodyChar, group and alternatives.

**Comment by mchakravarty** [comment]
Ok, here is a PR that exposes more helpers: https://github.com/mchakravarty/CodeEditorView/pull/34 
(I also changed scoping and naming to facilitate exposing them.) 

Would that serve your purpose?

**Comment by frios** [comment]
I will give that a try. Thank you. Might be a bit if I can't get to that this weekend as I am out of town next week.

But thank you.

**Comment by mchakravarty** [comment]
Ok, just let me know once you have got some feedback. Thanks!

**Comment by frios** [comment]
This is all compiling properly. I will next look at the details for how I can support my language choice.
Thank you. I will be in touch if I have any other questions.
